version: "3.9"
services:
  user1:
    container_name: user1
    build:
      context: ./docker
    volumes:
      - Matt_daemon:/app
    privileged: true

volumes:
 Matt_daemon:
   driver: local
   driver_opts:
     type: none
     device: .
     o: bind
